# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-12-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20191223_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_year',
            field=models.IntegerField(default=0, verbose_name='\u5de5\u4f5c\u5e74\u9650'),
        ),
    ]
