# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-12-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0'),
        ),
    ]
