# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-01-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_vedio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedio',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206)'),
        ),
    ]
